### PR TITLE
Change unmatch icon from heart to trash

### PR DESCRIPTION
**Pull request by SaturnusDJ**

### CODE REVIEW

**Comment by mayeaux** [comment]
Not now, I don't want a trash icon beside someone with the idea of throwing them in the trash. There's probably a better idea than just the heart but for now this isn't an improvement

**Comment by SaturnusDJ** [comment]
fa-delete is also an option.
Heart would be the last thing that would make me think of unmatch.
It's not like it's disrespectful, just needs to be clear. In my opinion it isn't now.

**Comment by mayeaux** [comment]
Another nice touch would be if we can give it the same hover effect you have in your branch so it looks clickable

**Comment by SaturnusDJ** [comment]
Yeah that's easy of course.

**Pull request closed without merging**
