### PR TITLE
Fix/change profile text

### PR DESCRIPTION
**Pull request by SaturnusDJ**
Breaks used by the writer of the profile text didn't render. This CSS
addon will fix that. ALso aligns text left, as in the mobile app.

### CODE REVIEW

**Comment by mayeaux** [comment]
Hey thanks for the PR @SaturnusDJ . Can you pull the latest changes from master branch down in your PR? Then I will check it out and get it merged, thanks!

**Comment by SaturnusDJ** [comment]
Hope it's fine now. Can't do anything else.
I'll continue working on CSS because the interface density looks really low.
Just some things I don't get. For example how class 'fa-briefcase' is called, but nowhere defined, yet removing it breaks some stuff.

**Comment by mayeaux** [comment]
Thanks @SaturnusDJ , will have a chance to check this out in the evening.

fa is font-awesome which is an icon library. Hopefully that's a solid enough hint, I don't have time to check the source atm as I'm at work now.

**Comment by SaturnusDJ** [comment]
Yeah, got it. Immediately replaced settings with fa-cog.
Several other changes have been made. I'll upload them to my branch soon. Probably dropping here automatically..

**Comment by mayeaux** [comment]
@SaturnusDJ yeah your commits will reflect here automatically when they're pushed to your branch

Are you able to verify that you're seeing errors come through when you access the Swipe page of the app? It's something I'd like to fix so the terminal isn't so polluted

**Comment by SaturnusDJ** [comment]
My nw.exe opens without terminal. If you tell me the setting to keep it open I will check.

**Comment by mayeaux** [comment]
Are you able to use the Toolbar to open an Inspect Element window and view the css when you edit it? And then you have to reboot the .exe everytime you change source?

Basically, if you install node, and nodewebkit, you should be navitage  to /desktop-app and then run `$ nodewebkit .` via terminal and have it open with a console. You're using Windows right?

**Comment by SaturnusDJ** [comment]
Correct I use inspector for most CSS changes. After editing the HTML file, the stuff needs a restart.

Maybe it is because I installed the latest stable version of nwjs.io. There is only nw.exe.
I also have the node package yes, but even that terminal doesn't launch nodewebkit.

**Comment by mayeaux** [comment]
Try running `$ npm install -g nwjs` or `$ npm install -g nodewebkit` and then running `$ nodewebkit .` from desktop-app folder

**Comment by SaturnusDJ** [comment]
Tried 2 minutes, no errors visible in terminal.

Something else: no matches/messages visible in any version (even the old compiled one). Will look again tomorrow.

**Comment by SaturnusDJ** [comment]
While trying to make a static top bar I'm running into some problems.

In the message window, when opening an empty chat, layout stays the same. When opening a chat where already has been talked, _something_ causes the layout to be rebuild, thereby ignoring the new static bar. What function causes this full 'rebuild'?

**Comment by mayeaux** [comment]
Hey @SaturnusDJ I won't have time to do this justice until the weekend. Can you post some screenshots on what you're trying to work towards? Before any big UI refactoring we should have a discussion of what our end UI/UX goals are.

**Comment by SaturnusDJ** [comment]
Screenshot: http://i67.tinypic.com/16ca15f.png

That's my thought about it. Make it more like the mobile app, without sacrificing the current benefits.

So I pulled the necessary content out of the swipe script/div to always be shown, and adjusted it.
But when clicking a contact in the message page, the 'static bar' disappears. (=Unstable branch. Master is ready to use, bugless.)

Later on, add some more fany things like show which page is active by leaving that icon colored and the others grey. CSS hover, etc.

**Comment by SaturnusDJ** [comment]
Error visible in console on Mac. This spawns every second:
Don't know about the conditions, maybe only when no one left to swipe.

> [1002:0309/110548:INFO:CONSOLE(101)] ""TypeError: Cannot read property 'childNodes' of undefined\n    at grabAllTextNodes (file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/twemoji.min.js:2:11481)\n    at parseNode (file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/twemoji.min.js:2:11898)\n    at Object.parse (file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/twemoji.min.js:2:13461)\n    at file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js:192:340\n    at file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js:108:201\n    at Object.\u003Canonymous\u003E (file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js:106:405)\n    at k.$digest (file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js:122:14)\n    at k.$apply (file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js:125:58)\n    at file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js:89:451"", source: file:///Users/SaturnusDJ/Documents/GitHub/mrmayfield/tinderplusplus/desktop-app/js/vendor/angular.min.js (101)

**Comment by SaturnusDJ** [comment]
A friend of mine showed this: https://gist.github.com/rtt/10403467
Lots of usefull things there I guess, e.g. Superlike.

Edit: I see you already found it. ;)

**Comment by SaturnusDJ** [comment]
I'm narrowing down my problem with the static bar disappearing when selecting a chat that already has messages in it.
Inside the index.html is `<div class="messages-list">`.
In there when I remove `-start` and `-end` from `ng-repeat`, the static bar stays, but some chat messages become rendered on the same line...
I removed the `ng-repeat-end` and put the clear class in the `ng-repeat-start` which is renamed to `ng-repeat`. Now that looks ok, but the chat text input area now is wrongly sized... Almost there...

Sorry to ask so much, I find it hard to get a grip on this stuff. It's like HTML and CSS yet totally mixed with JS etc.

**Comment by mayeaux** [comment]
Hey @SaturnusDJ I can't get that screenshot to open. Try posting it as a screenshot on this issue via: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/ . Also, I'd recommending getting a browser extension called 'Zenhub'. It has a lot of nice features and clicking to open up an explorer and select your screenshot is one of them.

Also, yes, you are receiving the same errors I am in the console. Even the way that we are doing package management right now by adding everything to source is wrong, I will probably add bower or browserify and then add them in a build script we can trigger from `$ npm start`.

Also, yes I am aware of that gist. It actually misses a ton of documentation, especially with the new endpoints that are up. We are currently using: https://github.com/alkawryk/tinderjs as our package to make calls to the Tinder client, but the package is unmaintained and has a couple issues. I'm going to add it to this organization and start maintaining it myself, also I will likely change the name of this project to Tinder-Desktop or Desktop-Tinder eventually. In the meantime I am going to start sniffing out the rest of these endpoints myself, one thing I really want to do is add the ability to change your photos directly from your desktop which Tinder supports now and would be a big boost. I also want to put in an auto-like feature ;) All in due time.

And yes AngularJS can take some wrapping your head around. I would watch a 50-60 minute tutorial of it online, it should run you over the basics and give you a good idea of what's going on. :)

**Comment by mayeaux** [comment]
Another thing I noticed is that you are still using the mrmayfield branch. I would clone this branch, from /tinderplusplus to start hacking, I think it's the one we'll use long term. Also, there is code added so that if you are using OSX the app should automatically restart when you save something in the codebase.

**Comment by SaturnusDJ** [comment]
tpp_staticbar

> By adding everything to source

What does that mean?

Ah ok, the old tinderjs, that's why adding new features isn't possible then.

Yeah I don't understand basic JS enough, let alone AngularJS plus the reason for needing ng-repeat-start and -end, while without seems to work too, even after reading the manual.
This project is really interesting, but also really hard.

I use tinderplusplus/tinderplusplus, but saved it as your username for folder management.

**Comment by mayeaux** [comment]
If you check: https://github.com/tinderplusplus/tinderplusplus/tree/master/desktop-app/js/vendor

You see that all this code is actually in the source code in the git repo. There should just be a file representing the packages needed (like we do with npm) and then we install from there.

**Comment by SaturnusDJ** [comment]
Because the 'compiled' versions don't need them?

**Comment by mayeaux** [comment]
No, they will still need them to build the compiled version. It's just improper to add them in source like this, and I suspect it is contributing to the errors being shown

**Comment by SaturnusDJ** [comment]
Ah, kind of 'unwritten rules.' Cool. I'll stick to the more 'front-end' stuff. :smile:

**Comment by SaturnusDJ** [comment]
@mrmayfield 
My experimental work is close to stable now. Won't push it too my master though, because the radical changes.
Try this if you have 2 minutes of time: https://github.com/SaturnusDJ/tinderplusplus/tree/unstable/1_Ready_to_use_versions

**Comment by mayeaux** [comment]
Hey @SaturnusDJ just checking this out now. Meanwhile I've renamed the organization `tinderjs` as myself and another dev are going to use this org to start maintaining the tinder client. I've invited you as a member of the org as well if you'd like to continue to contribute on tinderplusplus :)

**Comment by SaturnusDJ** [comment]
Ok I joined. Thanks for the invite.
Today I fixed all education/work elements appearing on the same line in swipe and profile. Also moved Instagram from username to education/work section. It'll be in unstable branch any moment. This fix will go in master too, so you'll see it here shortly.

**Comment by SaturnusDJ** [comment]
How's this one going?
Long time. It's proven stable for quite some weeks now.
desktop-app/js/tinder++.js and desktop-app/package.json can be ignored though.

Moreover, unstable is stable, (except for the superlike try out), and much better in my opinion.

**Comment by mayeaux** [comment]
I will come back to this soon. I will probably go piece by piece and grab certain functionality, I think some things could be merged right away like the typo I have in the readme with the old maintainer's username, but when I was playing around with this I found some frontend 'fixes' that I thought were actually a step in the wrong way. Tbh, my priority stream atm is backend functionality -> frontend functionality -> compilation functionality. Once I get the last couple backend features added that I want along with necessary bug fixes I will dedicate myself to frontend and at that point I'll look closely at the changes you've added here. Is anything here huge functionality changes or is it mostly cosmetic / ease of use things?

**Comment by SaturnusDJ** [comment]
What do you think is wrong?

I don't think it is possible to talk about 'huge changes' because there are a lot of small changes that together add to a better experience. Did you try my compiled version?

@amo13
What do you think about the version you are using now? Since it's a bit different from the last ('officially') compiled one.

**Comment by mayeaux** [comment]
It was a while ago that I checked it out things aren't as fresh in my mind. There was the one issue I pointed out and I think you fixed, also the top bar organization I thought was a step in the wrong direction, the current workflow for accessing settings with the Set Location option is better in my opinion. But like I said, we can go piece by piece in a bit. In the meantime, check out:

 https://slack.tinderjs.com

I've got us a Slack channel up and running :)

**Comment by SaturnusDJ** [comment]
In master not so much is changed. Set Location is unchanged.

It would be the best to pull soon because I'll change my unstable to master soon because current master is nothing but a 'wait to get pulled queue' at this moment.
As I understand you don't like my 'unstable' so that will end up as a different visual experience fork for people who like it.

Is there a solution to still let me send small pulls without having to have a fork? Maybe a branch in your repo with write rights?

Still finding out about Github. Just learned how to manually do pr merge.

**Comment by SaturnusDJ** [comment]
Unstable leading, as known.

**Pull request closed without merging**
