### PR TITLE
Disable js card rotation for smooth swiping experience

### PR DESCRIPTION
**Pull request by SaturnusDJ**

### CODE REVIEW

**Comment by stuwil** [comment]
@SaturnusDJ, is it any smoother using fixed (rather than random) values?

**Comment by stuwil** [comment]
Also, the lagginess has disappeared for me with #65...

**Comment by SaturnusDJ** [comment]
@stuwil 
Idk if fixed values will solve this.
Although your lag problem is solved, I think disabling this rotation will improve the smoothness even more.

**Comment by stuwil** [comment]
@SaturnusDJ: Can you please check the latest master and see if performance is still an issue for you here?

**Comment by SaturnusDJ** [comment]
Performance with card rotation disabled is still a lot better. Everyone try.

**Comment by stuwil** [comment]
Gonna close this for now, will reopen if anyone reports issues... thanks for testing!

**Comment by SaturnusDJ** [comment]
Pull this too as new mobile Tinder doesn't do dumb rotation also anymore. Looks like I was ahead of them.

**Pull request closed without merging**
