### PR TITLE
Add distance unit support for kilometres

### PR DESCRIPTION
**Pull request by stuwil**
Adds a kilometres option for distance units to the settings. I'm getting hit with #2, so I can't test the distance display for matches...

See mfkp/tinderplusplus#38

### CODE REVIEW

**Comment by mayeaux** [comment]
Will check this out right now. Can you do one thing though and log out and back in if that happens? I think it's due to the Tinder token expiring but I'm not 100% sure

**Comment by stuwil** [comment]
Tried that, no luck. Seems the GetHistory call from the Tinder client isn't returning matches...

""{\"matches\":[],\"blocks\":[\"scrubbed\"],\"lists\":[],\"deleted_lists\":[],\"liked_messages\":[],\"squads\":[],\"last_activity_date\":\"2016-04-08T18:15:10.284Z\"}""

**Comment by mayeaux** [comment]
Yeah that's definitely what's happening, but it's weird because it looks like the call is authenticated properly? I was thinking maybe the call was failing to authenticate. I can't seem to replicate this though my matches have worked properly everytime I've used the app. :\ Even if you logout, kill the app, and then restart it you have the same issue? I have a hunchy feeling that somehow the token isn't being refreshed if you logout (even though the cache _should_ be deleted).

**Comment by stuwil** [comment]
Randomly started appearing again. I suppose it might have been cached...

**Comment by mayeaux** [comment]
Can you add the distance filter to the icons on the messages part of index.html? I think we have to make it more modular as well so we can display for example `3 KM` instead of having it hardcoded at the moment to return `n kilometres`

Then I'll go ahead and give it a merge, seems to be working correctly, nice job. 👍

**Pull request merged**
