### PR TITLE
Split templates from index.html

### PR DESCRIPTION
**Pull request by stuwil**
Increases readability, and allows for inclusion of partials.

### CODE REVIEW

**Comment by mayeaux** [comment]
Long overdue, great idea

**Comment by SaturnusDJ** [comment]
Can the partial be a block?
Like this:

**Comment by stuwil** [comment]
@SaturnusDJ: The styling? It sure can, but this change is just for markup readability - took a peek at the current styles for it and ran away, scared.

**Comment by SaturnusDJ** [comment]
Just manipulate the div I guess. Good. :D

This indeed is better. I think this change is quite important to implement before starting front end changes.

**Pull request merged**
