### PR TITLE
UI Redesign

### LINKED ISSUE #57: Profile image / link missing
Following refactor-frontend merge

### LINKED ISSUE #58: Longer bios getting cut off by image grid
Following refactor-frontend merge

### PR DESCRIPTION
**Pull request by stuwil**
From @SaturnusDJ.

Fixes #57, fixes #58.

### CODE REVIEW

**Comment by stuwil** [comment]
@hanford @mrmayfield @run1t - This is @SaturnusDJ's work. Would like to get it merged ASAP given the impact, appreciate some testing here.

Couple things I've noticed:
1. ~~Discovery age slider looks glitched.~~
2. Superlikes count has disappeared.

**Comment by mayeaux** [comment]
Right, and the proximity slider looks a little weird too, but it's not definitely glitched like age slider.

There's a couple border things I don't like as well on the messages page. Otherwise:

Larger images look great
Border around small photos looks great

I'm a little so-so on the navbar, but it should work for now.

Had some issues with my connection, will check responsiveness in a bit

**Comment by mayeaux** [comment]
screen shot 2016-04-23 at 3 39 00 pm

Text runs off the screen in large bios

**Comment by SaturnusDJ** [comment]
Weird, that text thing is not supposed to happen at all. Never saw anything like it.

@mrmayfield 
Did you change window size for this to happen?

Really weird. I have large profile matches, but all text gets spaced out good. Send to next line if no space available.

**Comment by SaturnusDJ** [comment]
For superlikes count no space available in swipe.
Discovery has the space. Would be ok, it's not something you want to see/know all the time. We can implement to have a notification pop up when superlikes become available again.

**Comment by run1t** [comment]
@SaturnusDJ can you check the slack design channel, I posted a design proposition ;) And that's a good idea to implements notifications btw

**Comment by mayeaux** [comment]
We should just display superlikes remaining from the swipe page still. That's where it needs to be known, if you're out of superlikes it will already alert you.

**Pull request merged**
