### PR TITLE
Discovery settings

### PR DESCRIPTION
**Pull request by run1t**
capture d ecran 2016-04-14 a 16 30 35
capture d ecran 2016-04-14 a 16 30 24

### CODE REVIEW

**Comment by mayeaux** [comment]
:DDD Nice! Won't have time til the weekend to check lots of this out but it looks great, nice job! :D :+1:

**Comment by run1t** [comment]
capture d ecran 2016-04-15 a 03 33 46
capture d ecran 2016-04-15 a 03 34 14

**Comment by stuwil** [comment]
Hey @run1t,

Thanks for the PR. I've opened a pull request on your branch with some minor changes.

Would it make sense to move the Discovery Settings link under the existing Settings page?

Also, we need to add an entitlement check for Tinder Plus. The Passport widget doesn't work properly without it.

screen shot 2016-04-16 at 19 09 28

**Comment by SaturnusDJ** [comment]
I think the best will be to put these settings in a new page.
So we can split the Tinder account settings and settings that are only for this app ('user preferences').

**Comment by SaturnusDJ** [comment]
This one should be merged asap. My improved UI design is expecting a desktop-app/templates/discovery.html. :smiley:

**Pull request merged**
